[book]
authors = ["HeadMaxResh"]
language = "ru"
src = "src"
title = "Система для оценки стоимости сдачи квартир в аренду"

[build]
build-dir = "book"
create-missing = true

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
additional-css = ["src/_assets/custom.css"]
additional-js = []
